const ACTIONS = {
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT', 
  GET_TOKEN: "GET_TOKEN",
  TOKEN_FAIL: "TOKEN_FAIL",
  AUTH_FAIL: "AUTH_FAIL", 
  AUTH_ERROR: "AUTH_ERROR",
  TOKEN_ERROR: "TOKEN_ERROR",
  REFRESH_ERROR: "REFRESH_ERROR",
  LOGOUT: "LOGOUT",
  CLEAN:"CLEAN",
  ADDTICKER:"ADDTICKER",
  REMOVETICKER: "REMOVETICKER"
}

export default ACTIONS 

